# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: droid-variables

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install
  workingDirectory: src
  displayName: 'Install node dependencies'

- task: Gradle@2
  inputs:
    workingDirectory: 'src/android'
    gradleWrapperFile: 'src/android/gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleRelease'
  
- task: AndroidSigning@3
  displayName: 'Signing APK'
  inputs:
    apkFiles: '**/*.apk'
    apksign: true
    apksignerKeystoreFile: 'debug.keystore'
    apksignerKeystorePassword: '$(jarsignerKeystorePassword)'
    apksignerKeystoreAlias: 'react-native-pipeline-key'
    apksignerKeyPassword: '$(jarsignerKeyPassword)'

- script: mv src/android/app/build/outputs/apk/release/com.senkadir.$(Build.BuildNumber).apk
  displayName: 'Rename apk'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'src/android/app/build/outputs/apk/release/com.senkadir.$(Build.BuildNumber).apk'
    artifactName: drop
    publishLocation: 'container'